/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BillsImport } from './routes/bills'

// Create Virtual Routes

const MembersLazyImport = createFileRoute('/members')()
const GroupsLazyImport = createFileRoute('/groups')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MembersLazyRoute = MembersLazyImport.update({
  path: '/members',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/members.lazy').then((d) => d.Route))

const GroupsLazyRoute = GroupsLazyImport.update({
  path: '/groups',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/groups.lazy').then((d) => d.Route))

const BillsRoute = BillsImport.update({
  path: '/bills',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/bills': {
      preLoaderRoute: typeof BillsImport
      parentRoute: typeof rootRoute
    }
    '/groups': {
      preLoaderRoute: typeof GroupsLazyImport
      parentRoute: typeof rootRoute
    }
    '/members': {
      preLoaderRoute: typeof MembersLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  BillsRoute,
  GroupsLazyRoute,
  MembersLazyRoute,
])

/* prettier-ignore-end */
